// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alarma: typeof import('./components/Alarma.vue')['default']
    Alert: typeof import('./components/vuetifyComponentes/Alert.vue')['default']
    ComponentsNavigation: typeof import('./components/vuetifyComponentes/ComponentsNavigation.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    ErrorComponent: typeof import('./components/ErrorComponent.vue')['default']
    EVSelect: typeof import('./components/eComponents/EVSelect.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LoadingComponent: typeof import('./components/LoadingComponent.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PiniaFunctionsComponent: typeof import('./components/PiniaFunctionsComponent.vue')['default']
    PiniaTest: typeof import('./components/PiniaTest.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/vuetifyComponentes/Select.vue')['default']
    VuetifyTest: typeof import('./components/VuetifyTest.vue')['default']
  }
}

export {}
